### ISSUE TITLE
Does the wxMEdit.AppImage support saving configuration?

### ISSUE THREAD

**Issue by jcchen280** [VinnyVynce/wxMEdit.AppImage#1] opened 2021-04-17 14:13 UTC
I found that the setting was gone whenever I restart the wxMEdit.AppImage.
Is there a way to save the setting such as highlighting, font and view setting?
Thank you!

**Comment by beanbag420** [comment] 2021-04-18 18:51
Hi @jcchen280
The appimage should save your configs within your home directory. Make sure that your $HOME is configured and you have write/read access.
You should find a hidden folder in your home directory with the configs.
```
ls ~/.wxMEdit-3.1_FIX1/
FontWidth.dat  wxMEdit-3.1_FIX1.cfg
```
Also make sure that "Do not save settings to wxmedit.cfg when wxMEdit is closed" isn't checked in Tools > Options > Misc tab.

As of right now, I'm unable to reproduce your issue, lmk is any of these fixed your issue.
Thanks!

**Closed as completed** 2021-10-17 23:36 UTC
